export const ControllerKeyMap = {
  KEY_LEFT: 'left',
  KEY_TOP: 'up',
  KEY_RIGHT: 'right',
  KEY_BOTTOM: 'down',
  KEY_EXEC: 'w',
  KEY_CLEAN: 'a',
  KEY_FLAG: 's',
  KEY_TREASURE: 'd',
  KEY_FLAG_LEFT: 's+left',
  KEY_FLAG_TOP: 's+up',
  KEY_FLAG_RIGHT: 's+right',
  KEY_FLAG_BOTTOM: 's+down',
  KEY_TREASURE_LEFT: 'd+left',
  KEY_TREASURE_TOP: 'd+up',
  KEY_TREASURE_RIGHT: 'd+right',
  KEY_TREASURE_BOTTOM: 'd+down',
  KEY_COMMAND_UP: [
    { sequence: 's', action: 'keyup' },
    { sequence: 's+left', action: 'keyup' },
    { sequence: 's+up', action: 'keyup' },
    { sequence: 's+right', action: 'keyup' },
    { sequence: 's+down', action: 'keyup' },
    { sequence: 'd', action: 'keyup' },
    { sequence: 'd+left', action: 'keyup' },
    { sequence: 'd+up', action: 'keyup' },
    { sequence: 'd+right', action: 'keyup' },
    { sequence: 'd+down', action: 'keyup' },
  ],
};
export default ControllerKeyMap;
